/**
 * Coronavirus Tracker
 * API for tracking the global coronavirus (COVID-19, SARS-CoV-2) outbreak. Project page: https://github.com/ExpDev07/coronavirus-tracker-api.
 *
 * OpenAPI spec version: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Latest } from './latest';
import { Timelines } from './timelines';

/**
 * Location model.
 */
export interface Location { 
    id: number;
    country: string;
    countryCode: string;
    countryPopulation?: number;
    province?: string;
    county?: string;
    lastUpdated: string;
    coordinates: any;
    latest: Latest;
    timelines?: Timelines;
}