/**
 * Coronavirus Tracker
 * API for tracking the global coronavirus (COVID-19, SARS-CoV-2) outbreak. Project page: https://github.com/ExpDev07/coronavirus-tracker-api.
 *
 * OpenAPI spec version: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Timeline } from './timeline';

/**
 * Timelines model.
 */
export interface Timelines { 
    confirmed: Timeline;
    deaths: Timeline;
    recovered: Timeline;
}